# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.121.165:3306/lbytech
    username: root
    password: 1212qweasdzxc
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
