# 公共配置文件
spring:
  application:
    name: user-center-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.121.165:3306/lbytech
    username: root
    password: 1212qweasdzxc
  # session 失效时间
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: lax
        secure: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
